email: tiagofabre@gmail.com
baseurl: ""
url: "https://tiagofabre.github.io/"

github_username: tiagofabre
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

permalink: /posts/:title:output_ext
