# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tiago Fabre
email: tiagofabre@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Soluções de problemas que passei e considerações sobre o que tenho estudado.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tiagofabre.github.io/" # the base hostname & protocol for your site

github_username:  tiagofabre

# Build settings
markdown: kramdown
